# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newform',
            name='Status',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
