# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181120_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newform',
            name='Update1',
            field=models.TextField(max_length=5000),
        ),
    ]
