# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-04 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181120_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newform',
            name='Update1',
        ),
        migrations.RemoveField(
            model_name='newform',
            name='Update2',
        ),
        migrations.RemoveField(
            model_name='newform',
            name='Update3',
        ),
        migrations.RemoveField(
            model_name='newform',
            name='Update4',
        ),
        migrations.RemoveField(
            model_name='newform',
            name='Update5',
        ),
        migrations.RemoveField(
            model_name='newform',
            name='Update6',
        ),
        migrations.AlterField(
            model_name='newform',
            name='ArrivalDate',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='newform',
            name='ArrivalTime',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='newform',
            name='DepatureDate',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='newform',
            name='Depaturetime',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='newform',
            name='GoodsDescription',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='newform',
            name='GoodsTo',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='newform',
            name='GoodsareFrom',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='newform',
            name='RecieverAddress',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='newform',
            name='RecieverName',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='newform',
            name='SenderAddress',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='newform',
            name='SenderName',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='newform',
            name='referenceID',
            field=models.CharField(max_length=2000),
        ),
    ]
