# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-26 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_secure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newform',
            old_name='ArrivalTime',
            new_name='Destination',
        ),
        migrations.RenameField(
            model_name='newform',
            old_name='Depaturetime',
            new_name='Origin',
        ),
        migrations.RemoveField(
            model_name='newform',
            name='GoodsTo',
        ),
        migrations.RemoveField(
            model_name='newform',
            name='GoodsareFrom',
        ),
        migrations.AlterField(
            model_name='newform',
            name='ArrivalDate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='newform',
            name='DepatureDate',
            field=models.DateTimeField(blank=True),
        ),
    ]
