# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190227_0258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newform',
            old_name='GoodsTo',
            new_name='Courier',
        ),
        migrations.RenameField(
            model_name='newform',
            old_name='GoodsareFrom',
            new_name='Destination',
        ),
        migrations.AddField(
            model_name='newform',
            name='InTransit',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='newform',
            name='Origin',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='newform',
            name='ScheduledFlight',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
