# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190326_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='secure',
            name='InTransit',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='secure',
            name='ScheduledFlight',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
