# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-17 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SenderName', models.CharField(max_length=250)),
                ('SenderAddress', models.CharField(max_length=250)),
                ('RecieverName', models.CharField(max_length=250)),
                ('RecieverAddress', models.CharField(max_length=250)),
                ('referenceID', models.CharField(max_length=250)),
                ('GoodsareFrom', models.CharField(max_length=250)),
                ('GoodsTo', models.CharField(max_length=250)),
                ('DepatureDate', models.CharField(max_length=250)),
                ('Depaturetime', models.CharField(max_length=250)),
                ('ArrivalDate', models.CharField(max_length=250)),
                ('ArrivalTime', models.CharField(max_length=250)),
                ('GoodsDescription', models.TextField(max_length=1000)),
                ('Status', models.TextField(max_length=5000)),
            ],
        ),
    ]
